#!/bin/bash

card=$1
rev=$2
status=$3
message=$4
editor=`whoami`




#what is $result?


#insert into Database ACCMTCLog reason for revision
SQLUSER="carlo" 
SQLPASS="mpla" #or is it mplapassword? 
SQLHOST="127.0.0.1" 
SQLDATE=`date +%Y-%m-%d`
SQLDATE=${SQLDATE}" "
SQLDATE=${SQLDATE}`date +%H:%M:%S`
SQLDB="MTC" 
SQLTBL="ACCMTCLog" 
echo "INSERT INTO ACCMTCLog VALUES (NULL,'${SQLDATE}','${card}','$rev','$status','$editor','$message');" | mysql -u$SQLUSER -p$SQLPASS -h$SQLHOST $SQLDB;
		
#				echo "`date +%Y-%m-%d` `date +%H:%M:%S`,${card},$result,DRAFT,$username,$Reason (sent to $username)" >> System/log.csv
echo "$card change logged - \"$message\" by $editor"


