#!/bin/bash
#!/usr/bin/env Rscript

#################################################
# ask for data (paths of AMM, MS, and Output Files.
# check that these are valid paths
#################################################

pathtoMS=$1
pathtoAMM=$2
actype=$3


source CardVariables

rm TCRef.csv 2> /dev/null
rm var.txt 2> /dev/null
rm AMMGRAPHIC.SGM 2> /dev/null
rm AMMTASK.SGM 2> /dev/null


# Default Values
#pathtoAMM="./AMM.SGM"
#pathtoMS="./MS.xls"
pathtoOutput="$pathtoFinalCards/NewCards"
#pathtoNewCards="/media/carlo/DATA/AircraftEngineering/MTC/$actype/$actype FINAL CARDS/NewCards/"



#################################################
# Process the AMM.SGM File
#################################################

# This processes the AMM.SGM to be :
# 1. one Task per line
if [ ! -f "AMMTASK.SGM" ];
then
echo "Creating AMMTASK.SGM"
cat "$pathtoAMM" | tr '\n' ' ' | sed 's#<TASK CHAPNBR#\n<TASK CHAPNBR#g' | grep "^<TASK CHAPNBR" > AMMTASK.SGM
fi

# 2. consolidate the GRAPHICS.sgm
if [ ! -f "AMMGRAPHIC.SGM" ];
then
echo "Creating AMMGRAPHIC.SGM"
cat "$pathtoAMM" | tr '\n' ' ' | sed 's#<GRAPHIC CHAPNBR#\n<GRAPHIC CHAPNBR#g' | sed 's#</GRAPHIC>#</GRAPHIC>\n#g' | grep "^<GRAPHIC CHAPNBR" > AMMGRAPHIC.SGM
fi

# Put variables to var.txt so that it will be usable by the R script JITCG.R
printf "\"pathtoAMM\",\"pathtoMS\",\"pathtoOutput\"\n" > var.txt
printf "\"$pathtoAMM\",\"$pathtoMS\",\"$pathtoOutput\"\n" >> var.txt

#################################################
# Run CreateNewCardDeck.R to create the Initial Output Cards and the TCRef.csv
#################################################

echo -e "Running R Script: Creating Header for Task Cards"
###########Insert R Code Here
Rscript "$SysFiles/CreateNewCardDeck.R"


#################################################
# Read TCRef.csv and additionally add to the Output Cards the AMM body from AMMTASK.SGM
#################################################
echo -e "Attaching AMM References"

cat "TCRef.csv" | sed 's/"//g'| while IFS=, read -r f1 f2;
	do
	if [ "$f2" != "" ] 
		then
		grep "KEY=\"EN$f2" ./AMMTASK.SGM >> "$pathtoOutput/$f1.sgm"
		fi
		echo "</TCBODY>" >> "$pathtoOutput/$f1.sgm"
#		echo -e "\t$pathtoOutput/$f1.sgm"
done

#################################################
# Redo All of the Output Files to include Sign Offs
#################################################

echo -e "Writing Sign Offs"

cat "TCRef.csv" | sed 's/"//g'| while IFS=, read -r f1 f2;
	do
	{ 
	cat "$pathtoOutput/$f1.sgm" | sed 's#</SUBTASK>#\n<SO ID="1"></SO>\n</SUBTASK>#g' > tmpfile
	} 
	mv tmpfile "$pathtoOutput/$f1.sgm"
#	echo -e "\t$pathtoOutput/$f1.sgm"

done

#################################################
# Attach Graphic References
#################################################

echo -e "Attaching Graphic References"

#bad to assume to work on all sgm files	
cat "TCRef.csv" | sed 's/"//g'| while IFS=, read -r f1 f2;
	do
	result=$(grep -o "GNBR=\"[^\"]*\"" "$pathtoOutput/$f1.sgm")
#	echo -e "\t$pathtoOutput/$f1.sgm,$result" | tr '\n' ','
#	echo -e "\n"
	if [ "$result" != "" ] 
		then
			echo -e "$result" | while read -r graphics;
				do
				grep "$result" ./AMMGRAPHIC.SGM >> "tmpfile"
				done
			cat "tmpfile" | sort -u > "tmpfile2"
	 		rm "tmpfile"
			cat "tmpfile2" >> "$pathtoOutput/$f1.sgm"
			rm "tmpfile2"
		fi
	echo -e "</TASKCARD>" >> "$pathtoOutput/$f1.sgm"

done

rm TCRef.csv 2> /dev/null
rm var.txt 2> /dev/null
rm AMMGRAPHIC.SGM 2> /dev/null
rm AMMTASK.SGM 2> /dev/null
echo -e "Finished Creating Your Deck of Cards!!"
#echo -e ""
#echo -e "Moving Cards to NewCards Deck!!"
#mv $pathtoOutput/*.sgm $pathtoNewCards

# Make Revision Control List

